### PR TITLE
Feature/bbss 4 d

### PR DESCRIPTION
**Pull request by xbuffat**
## Description
Implemented strong-strong 4D beam-beam with the pipeline following the 6D implementation

Closes # .

## Checklist

Mandatory: 

- [ ] I have added tests to cover my changes
- [ ] All the tests are passing, including my new ones
- [ ] I described my changes in this PR description

Optional:

- [ ] The code I wrote follows good style practices (see [PEP 8](https://peps.python.org/pep-0008/) and [PEP 20](https://peps.python.org/pep-0020/)).
- [ ] I have updated the docs in relation to my changes, if applicable
- [ ] I have tested also GPU contexts

### CODE REVIEW

**Comment by giadarol** [comment]
@xbuffat thanks for this. Could you please add a test in the test suite for this feature?

**Comment by giadarol** [comment]
Thank you! We need to add a test to the suite before this can be merged

**Comment by xbuffat** [comment]
Done!

**Comment by xbuffat** [comment]
Once this is merged, issues https://github.com/xsuite/xsuite/issues/237 and https://github.com/xsuite/xsuite/issues/236 can be closed

**Review by giadarol — APPROVED** [review]

**Pull request merged**
